apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        pullstrategy:
        ports:
        - containerPort: {{.Values.container.port}}
        env:
        - name: Logging__LogLevel__Default
          value: "Debug"
        - name: Logging__LogLevel__System
          value: "Information"
        - name: Logging__LogLevel__Microsoft
          value: "Information"

        - name: Services__Recommendation__Uri
          value: {{quote .Values.env.Services__Recommendation__Uri}}
        - name: Services__Recommendation__Port
          value: {{quote .Values.env.Services__Recommendation__Port}}
        - name: DatabaseConnectionString
          value: {{quote .Values.env.DatabaseConnectionString}}
        - name: TMDB__ApiKey
          value: {{quote .Values.env.TMDB__ApiKey}}
