FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 3010

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY Recommendation.Database/Recommendation.Database.csproj Recommendation.Database/
RUN dotnet restore "Recommendation.Database/Recommendation.Database.csproj"
COPY Recommendation.Service/Recommendation.Service.csproj Recommendation.Service/
RUN dotnet restore "Recommendation.Service/Recommendation.Service.csproj"
COPY . .
WORKDIR /src/Recommendation.Service
RUN dotnet build "Recommendation.Service.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Recommendation.Service.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Recommendation.Service.dll",  "--environment=Release"]