apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}-deployment
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image: {{.Values.image}}
        ports:
        - containerPort: {{.Values.container.port}}
        env:
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: Logging__LogLevel__System
          value: "Information"
        - name: Logging__LogLevel__Microsoft
          value: "Information"
          
        - name: DatabaseConnectionString
          value: {{quote .Values.env.DatabaseConnectionString}}
        - name: RedisConnectionString
          value: {{quote .Values.env.RedisConnectionString}}
