apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cluster-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{index .Values "recommendation-client" "name"}}-service
          servicePort: {{index .Values "recommendation-client" "service" "port"}}